---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.17.1
    ports:
    - 8080:8080
    restart: on-failure:0
    volumes:
    - ./backups:/tmp/backups
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,backup-filesystem'
      BACKUP_FILESYSTEM_PATH: '/tmp/backups'
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_EXPERIMENTAL_BM25: 'true'
  t2v-transformers:
    image: cshorten/text2vec-sentencetransformers:all-MiniLM-L6-v2
    environment:
      ENABLE_CUDA: '0'
...